import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  horizenChainSidebar: [{ type: "autogenerated", dirName: "horizen-chain" }],
  velaSidebar: [{ type: "autogenerated", dirName: "vela" }],
  tutorialsSidebar: [{ type: "autogenerated", dirName: "tutorials" }],
  governanceSidebar: [{ type: "autogenerated", dirName: "governance" }],
  ecosystemSidebar: [{ type: "autogenerated", dirName: "ecosystem" }],
};

export default sidebars;
